CREATE TABLE cliente(
IdCLiente INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
Nome VARCHAR(100) NOT NULL,
Sobrenome VARCHAR(100) NOT NULL,
DataNasc TIMESTAMP NOT NULL,
Rg VARCHAR (13) NOT NULL,
Cpf VARCHAR (11) NOT NULL,
Sexo VARCHAR(10) NOT NULL,
EstadoCivil VARCHAR (10),
Email VARCHAR(255),
Telefone  VARCHAR (30) NOT NULL,
Cep VARCHAR (8) NOT NULL,
Endereco VARCHAR (255) NOT NULL,
NumEnd VARCHAR (40)NOT NULL,
Complemento VARCHAR(255),
Bairro VARCHAR (30) NOT NULL ,
Cidade VARCHAR (30) NOT NULL,
Estado VARCHAR (30) NOT NULL,
enabled BOOLEAN
);

CREATE TABLE produto(
CodProduto BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
Modelo VARCHAR(100) NOT NULL,
Tamanho VARCHAR(2) NOT NULL,
Marca VARCHAR(100) NOT NULL,
Cor VARCHAR(20) NOT NULL,
Genero VARCHAR(10) NOT NULL,
Preco INTEGER NOT NULL,
enabled BOOLEAN
);
 
